In [41]:
import numpy as np
from sklearn.datasets import load_breast_cancer
import pandas as pd


In [53]:
data = load_breast_cancer()
x = pd.DataFrame(data.data,columns=data.feature_names)
y = pd.Series(data.target)
y

0      0
1      0
2      0
3      0
4      0
      ..
564    0
565    0
566    0
567    0
568    1
Length: 569, dtype: int64

In [43]:
sample_b = x[y==1].iloc[:3].values
sample_b

array([[1.354e+01, 1.436e+01, 8.746e+01, 5.663e+02, 9.779e-02, 8.129e-02,
        6.664e-02, 4.781e-02, 1.885e-01, 5.766e-02, 2.699e-01, 7.886e-01,
        2.058e+00, 2.356e+01, 8.462e-03, 1.460e-02, 2.387e-02, 1.315e-02,
        1.980e-02, 2.300e-03, 1.511e+01, 1.926e+01, 9.970e+01, 7.112e+02,
        1.440e-01, 1.773e-01, 2.390e-01, 1.288e-01, 2.977e-01, 7.259e-02],
       [1.308e+01, 1.571e+01, 8.563e+01, 5.200e+02, 1.075e-01, 1.270e-01,
        4.568e-02, 3.110e-02, 1.967e-01, 6.811e-02, 1.852e-01, 7.477e-01,
        1.383e+00, 1.467e+01, 4.097e-03, 1.898e-02, 1.698e-02, 6.490e-03,
        1.678e-02, 2.425e-03, 1.450e+01, 2.049e+01, 9.609e+01, 6.305e+02,
        1.312e-01, 2.776e-01, 1.890e-01, 7.283e-02, 3.184e-01, 8.183e-02],
       [9.504e+00, 1.244e+01, 6.034e+01, 2.739e+02, 1.024e-01, 6.492e-02,
        2.956e-02, 2.076e-02, 1.815e-01, 6.905e-02, 2.773e-01, 9.768e-01,
        1.909e+00, 1.570e+01, 9.606e-03, 1.432e-02, 1.985e-02, 1.421e-02,
        2.027e-02, 2.968e-03, 1.023e

In [44]:
sample_m = x[y==0].iloc[:3].values
sample_m

array([[1.799e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01, 2.776e-01,
        3.001e-01, 1.471e-01, 2.419e-01, 7.871e-02, 1.095e+00, 9.053e-01,
        8.589e+00, 1.534e+02, 6.399e-03, 4.904e-02, 5.373e-02, 1.587e-02,
        3.003e-02, 6.193e-03, 2.538e+01, 1.733e+01, 1.846e+02, 2.019e+03,
        1.622e-01, 6.656e-01, 7.119e-01, 2.654e-01, 4.601e-01, 1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, 1.326e+03, 8.474e-02, 7.864e-02,
        8.690e-02, 7.017e-02, 1.812e-01, 5.667e-02, 5.435e-01, 7.339e-01,
        3.398e+00, 7.408e+01, 5.225e-03, 1.308e-02, 1.860e-02, 1.340e-02,
        1.389e-02, 3.532e-03, 2.499e+01, 2.341e+01, 1.588e+02, 1.956e+03,
        1.238e-01, 1.866e-01, 2.416e-01, 1.860e-01, 2.750e-01, 8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, 1.203e+03, 1.096e-01, 1.599e-01,
        1.974e-01, 1.279e-01, 2.069e-01, 5.999e-02, 7.456e-01, 7.869e-01,
        4.585e+00, 9.403e+01, 6.150e-03, 4.006e-02, 3.832e-02, 2.058e-02,
        2.250e-02, 4.571e-03, 2.357e

In [45]:
sample = np.vstack([sample_b,sample_m])
sample

array([[1.354e+01, 1.436e+01, 8.746e+01, 5.663e+02, 9.779e-02, 8.129e-02,
        6.664e-02, 4.781e-02, 1.885e-01, 5.766e-02, 2.699e-01, 7.886e-01,
        2.058e+00, 2.356e+01, 8.462e-03, 1.460e-02, 2.387e-02, 1.315e-02,
        1.980e-02, 2.300e-03, 1.511e+01, 1.926e+01, 9.970e+01, 7.112e+02,
        1.440e-01, 1.773e-01, 2.390e-01, 1.288e-01, 2.977e-01, 7.259e-02],
       [1.308e+01, 1.571e+01, 8.563e+01, 5.200e+02, 1.075e-01, 1.270e-01,
        4.568e-02, 3.110e-02, 1.967e-01, 6.811e-02, 1.852e-01, 7.477e-01,
        1.383e+00, 1.467e+01, 4.097e-03, 1.898e-02, 1.698e-02, 6.490e-03,
        1.678e-02, 2.425e-03, 1.450e+01, 2.049e+01, 9.609e+01, 6.305e+02,
        1.312e-01, 2.776e-01, 1.890e-01, 7.283e-02, 3.184e-01, 8.183e-02],
       [9.504e+00, 1.244e+01, 6.034e+01, 2.739e+02, 1.024e-01, 6.492e-02,
        2.956e-02, 2.076e-02, 1.815e-01, 6.905e-02, 2.773e-01, 9.768e-01,
        1.909e+00, 1.570e+01, 9.606e-03, 1.432e-02, 1.985e-02, 1.421e-02,
        2.027e-02, 2.968e-03, 1.023e

In [46]:
from scipy.spatial.distance import euclidean,cityblock,cosine,chebyshev,mahalanobis
cov = np.cov(x.values.T)
invcov = np.linalg.inv(cov)

In [47]:
distance = []
for i in range(len(sample)):
      for j in range(i+1,len(sample)):
            p = sample[i]
            q = sample[j]
            distance_euclidean = euclidean(p,q) 
            distance_manhatan = cityblock(p,q)
            distance_cosine = cosine(p,q)
            distance_cheby = chebyshev(p,q)
            distance_maha = mahalanobis(p,q,invcov)
            distance.append({"اقلیدسی":distance_euclidean,"منهتن":distance_manhatan,"کسینوسی":distance_cosine,
                              "بزرگترین اختلاف":distance_cheby,"فاصله با توجه به پراکندگی":distance_maha})
distance_dataframe = pd.DataFrame(distance) 
print(distance_dataframe)                           

        اقلیدسی        منهتن   کسینوسی  بزرگترین اختلاف  \
0     93.573481   146.166790  0.000254             80.7   
1    494.571181   773.490542  0.003345            396.3   
2   1387.374891  2022.714836  0.024296           1307.8   
3   1461.149811  2185.910759  0.004691           1244.8   
4   1187.753420  1832.112813  0.003193            997.8   
5    402.284928   636.260162  0.002108            315.6   
6   1479.185295  2168.459870  0.029043           1388.5   
7   1554.498609  2326.749765  0.007014           1325.5   
8   1281.129509  1972.710189  0.005215           1078.5   
9   1862.826248  2788.210502  0.039302           1704.1   
10  1953.970842  2959.277885  0.015256           1641.1   
11  1681.019847  2605.559999  0.012262           1394.1   
12   341.730262   527.555005  0.009837            325.0   
13   376.455765   638.735341  0.011900            310.0   
14   276.776239   409.471964  0.000286            247.0   

    فاصله با توجه به پراکندگی  
0                    5.